### ISSUE TITLE
requirements for training

### ISSUE THREAD

**Issue by MenglinQiu** [nfraehr/Hybrid_LSG_model#1]
Hi Fraehr,  It is a excellent work!  I am unable to run "SparseGPmodel-training.py" based on the data and computational demand given in the paper.  Process is always killed without error log.  Can you give me some suggestions?  Is 64G RAM enough? Thank for your help!

**Comment by nfraehr** [comment]
This is hard to answer without more information of where in the code the issue occurs. I suggest you try to run the code in sections to explore where it goes wrong.

To answer your question, 64GB RAM is enough. Other options that could be the issue, as I see it, are:
1) Wrong version of packages. Make sure to use gpflow=2.5.2, with tensorflow=2.10.0. I have just tested using these and it works. Also ensure to use python=3.9
2) Problems with hardware and software interactions. For example check your CUDA installation.

**Comment by MenglinQiu** [comment]
Thank you for your answer. I'll do it as you suggested!
